name: sixth_workflow

on: 
  push:
  workflow_dispatch:
  schedule:
  - cron: '30/5 * * * *'

jobs:
    job_A:
        name: Job A
        runs-on: ubuntu-latest
        steps:
            - name: Triggering a job
              run: |
                date
                echo "Job A is running"
                echo "This job is triggered by a ${{ github.event_name }} event"
