name: fifth_workflow

on: push

env:
    OWNER_NAME: ${{ github.event.repository.owner.login }}
    WORKFLOW_NAME: ${{ github.workflow }}

jobs:
    job_A:
        name: Job A
        runs-on: ubuntu-latest
        env: 
            JOB_NAME: job_A
        steps:
            - name: Print environment variables
              env: 
                STEP_NAME: print_env
              run: |
                echo "Workflow name: ${{ env.WORKFLOW_NAME }}"
                echo "Owner name: ${{ env.OWNER_NAME }}"
                echo "Job name: ${{ env.JOB_NAME }}"
                echo "Step name: ${{ env.STEP_NAME }}"

            - name: Print all envs
              env: 
                STEP_NAME: print_all_env
              run: |
                printenv

            - name: Login to Docker Hub
              env: 
                STEP_NAME: docker_login
              # run: |
              #   docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
              #   echo "Docker login successful"
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Check secrets
              run: |
                echo "DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}"
                echo "DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}"
