name: eighth_workflow

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:

jobs:
    job_A:
        name: Job A
        strategy:
          fail-fast: false
          max-parallel: 2
          matrix:
            os: [ubuntu-latest, ubuntu-22.04]
            user: [yatharth, alpha]
            exclude:
              - os: ubuntu-22.04
                user: alpha
            include:
              - os: ubuntu-latest
                user: beta
        runs-on: ${{ matrix.os }}
        steps:
            - name: Get system information
              run: |
                cat /etc/os-release
                echo "OS version: ${{ runner.os }}"
                echo "OS architecture: ${{ runner.arch }}"
