name: Scheduled Workflow

on: 
    workflow_dispatch:
    schedule:
        - cron: "47 16 11 * *"

jobs:
    job_A:
        runs-on:  ubuntu-latest
        timeout-minutes: 2
        concurrency:
            group: job_a
            cancel-in-progress: true
        steps:
            - name: Welcome message
              run: echo 'My First Scheduled Github Actions Job'

            - name: Check date and time
              run: date

            - name: Increase pipeline time
              timeout-minutes: 1
              run: sleep 20

            - name: Increase pipeline time again
              timeout-minutes: 1
              run: sleep 200
