name: Scheduled Workflow

on: 
    workflow_dispatch:
    schedule:
        - cron: "17 15 11 * *"

jobs:
    job_A:
        runs-on:  ubuntu-latest
        steps:
            - name: Welcome message
              run: echo 'My First Scheduled Github Actions Job'

            - name: Check date and time
              run: date
