name: eighth_workflow

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:

jobs:
    job_A:
        name: Job A
        strategy:
          fail-fast: false
          max-parallel: 2
          matrix:
            os: [ubuntu-latest, ubuntu-22.04]
            user: [yatharth, alpha]
            exclude:
              - os: ubuntu-22.04
                user: alpha
            include:
              - os: ubuntu-latest
                user: beta
        runs-on: ${{ matrix.os }}
        steps:
            - name: Get system information
              run: |
                cat /etc/os-release
                echo "OS version: ${{ runner.os }}"
                echo "OS architecture: ${{ runner.arch }}"
                echo "${{ matrix.user }}"

    job_build:
      name: Build
      strategy:
        matrix:
          os: 
          - ubuntu-latest
          - ubuntu-22.04
          lang:
          - name: java
            directory: java
            command: gradlew build
          - name: node
            directory: node
            command: npm install
          - name: python
            directory: python
            command: pip install -r requirements.txt
          exclude:
          - os: ubuntu-22.04
            lang: 
              name: node
              directory: node
              command: npm install
          include:
          - os: ubuntu-22.04
            lang:
              name: php
              directory: php
              command: php install
      runs-on: ${{ matrix.os }}
      steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Build with ${{ matrix.lang.name }}
            run: |
              mkdir -p ${{ matrix.lang.directory }}
              cd ${{ matrix.lang.directory }}
              echo ${{ matrix.lang.command }}
    