name: seventh_workflow

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on: 
  push:

jobs:
    job_A:
        name: Job A
        runs-on: ubuntu-latest
        steps:
            - name: Long running job
              run: |
                echo "Job A is running"
                sleep 600s
