name: second_workflow

on: push

jobs:
    job_A:
        name: Job A
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v4

            - name: Read Readme
              run: |
                pwd
                ls -a
                cat README.md

            - name: Run cowsay
              run: |
                sudo apt-get install -y cowsay
                cowsay --version
                cowsay -f dragon "Hello from Job A"


