name: twelth_workflow

on:
  push:

jobs:
  job_A:
    name: Job A
    runs-on: ubuntu-latest
    outputs:
      A_HOST: ${{ steps.check-replaced-file.outputs.JOB_A_HOSTNAME }}
    steps:
      - name: Set dynamic environment variables
        id: set-env
        run: |
          echo "NAME=$(hostname)" >> $GITHUB_ENV

      - name: Check environment variables
        id: check-env
        run: |
          echo "Environment variables:"
          echo "NAME: ${{ env.NAME }}"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Replace token in file
        id: replace-token
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '__'
          tokenSuffix: '__'
          files: '["files/*.txt"]'
        env:
          NAME: ${{ env.NAME }}
          LOCATION: 'Delhi'

      - name: Check replaced file
        id: check-replaced-file
        run: |
          echo "Replaced file content:"
          cat files/*.txt
          echo "JOB_A_HOSTNAME=$(hostname)" >> $GITHUB_OUTPUT

  job_B:
    name: Job B
    runs-on: ubuntu-latest
    needs: job_A
    steps:
      - name: Check replaced file content
        id: check-file-content
        run: |
          echo "A_HOSTNAME: ${{ needs.job_A.outputs.A_HOST }}"
          echo "B_HOSTNAME: $(hostname)"
