name: second_workflow

on: push

jobs:
    job_A:
        name: Job A
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v4

            - name: Read Readme
              run: |
                ls -a
                cat README.md